services:
  marketplace:
    image: marketplace
    container_name: marketplace-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - marketplace
    environment:
      - DBUSER=postgres
      - DBPASSWORD=pgpassword
      - DBHOST=marketplace-postgres:5432
      - DBNAME=marketplace
    command: bash -c "
        alembic upgrade head
        && gunicorn --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker app.categories.routers.main:app
      "    
       

  postgres:
    container_name: marketplace-postgres
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      PGUSER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpassword}
      POSTGRES_DB: ${POSTGRES_DB:-marketplace}
      PGDATA: /data/postgres
    volumes:
      - ./pg_data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - marketplace
    restart: unless-stopped

networks:
  marketplace:
