"""path field added

Revision ID: db9e636e6c2f
Revises: 91bff2935265
Create Date: 2025-04-18 17:27:21.840497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9e636e6c2f'
down_revision: Union[str, None] = '91bff2935265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('path', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_categories_path'), 'categories', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_path'), table_name='categories')
    op.drop_column('categories', 'path')
    # ### end Alembic commands ###
